title = '九师傅的 TRPG 分享小站'
baseURL = 'https://www.rhinonine.cn/'
languageCode = 'en-us'
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] 
theme = "hugo-blog-awesome"

[services]
  [services.googleAnalytics]
    id = 'G-J0PQS7E9QS' 

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[menu]
  [[menu.main]] 
    pageRef="rules"
    name = '规则'
    url = '/rules/'
    weight = 10
 [[menu.main]] 
    pageRef="modules"
    name = '模组'
    url = '/modules/'
    weight = 20
 [[menu.main]]
    pageRef="tools"
    name = '工具'
    url = '/tools/'
    weight = 30
   [[menu.main]]
    pageRef="resources"
    name = '资源'
    url = '/resources/'
    weight = 40
  [[menu.main]]
    pageRef="about"
    name = '关于'
    url = '/about/'
    weight = 50

[taxonomies]
tag = "tags"
category = "categories"

[params]
  sitename = "sitename"
  defaultColor = "dark" 
  description = "要做海鸥，要除刁民"

[params.author]
  avatar = "avatar.png"
  intro = "The Universe in a Dice"
  name = "Rhino Nine"
  description = "Another Day Another Roll"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Rhino-Nine"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"
